---
- name: Installing vagrant packages using apt
  become: true
  apt:
    pkg: "vagrant"
    update_cache: yes
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: Installing vagrant packages using yum
  become: true
  yum:
    pkg: "vagrant"
    update_cache: yes
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Installing vagrant packages using pacman
  pacman:
    name: "vagrant"
    state: present
  when: ansible_distribution == 'MacOSX'
